### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-vyos#9]
Before making it official we have to ensure documentation is updated. Could you take a look?

https://napalm.readthedocs.io/en/latest/support/index.html

Also, you will need a PR to tell napalm this is py3 compliant. Something like this:

https://github.com/napalm-automation/napalm-base/pull/177/files

**Comment by dbarrosop** [comment]
Oh, and it has to be added here as well:

https://github.com/napalm-automation/napalm/blob/develop/requirements.txt

**Comment by dbarrosop** [comment]
We have to consolidate those but while we work on making them py3 compliant we need to keep them separate : (

**Comment by dbarrosop** [comment]
Note that the getters support matrix will be filled automatically as soon as we officially launch the driver so you can ignore that part : )

**Comment by ppieprzycki** [comment]
Here are PR's

Here travis is having problem with installing napalm-vyos package
https://github.com/napalm-automation/napalm/pull/344

Support in ansible module
https://github.com/napalm-automation/napalm-ansible/pull/44

added comment, If needed separate PR probably would be easier if this pr is merged first before next similar
https://github.com/napalm-automation/napalm-base/pull/177

**Comment by dbarrosop** [comment]
Ok, everything is done : )

Here is the docs (we have to merge with master soon):

https://napalm.readthedocs.io/en/develop/support/index.html#getters-support-matrix

**Comment by dbarrosop** [comment]
Let's close this one, reopen it if you have any doubt.

Thanks for the hard work : )
